# Generated by Django 4.2.7 on 2026-03-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-last_message_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_ca_id_af2fee_idx",
            old_name="conversations_ca_statu_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_sme_id_1af2c8_idx",
            old_name="conversations_sme_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="conversatio_last_me_99c95c_idx",
            old_name="conversations_last_me_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_convers_3ebb41_idx",
            old_name="messages_conversation_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_sender__6ae55a_idx",
            old_name="messages_sender_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="messages_is_read_6a69c0_idx",
            old_name="messages_is_read_idx",
        ),
    ]
