# Generated by Django 4.2.7 on 2025-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
