# Generated by Django 4.2.7 on 2025-12-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_services', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.chatsession'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_services.aimodel'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='related_documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='related_transactions',
            field=models.ManyToManyField(blank=True, to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL),
        ),
    ]
