# Generated by Django 4.2.7 on 2025-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_calendar',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('gst_filing', 'GST Filing'), ('tds_deduction', 'TDS Deduction'), ('itr_filing', 'ITR Filing'), ('audit_requirement', 'Audit Requirement'), ('documentation', 'Documentation')], max_length=30)),
                ('description', models.TextField()),
                ('conditions', models.JSONField(default=dict)),
                ('consequences', models.TextField()),
                ('due_period', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_rules',
            },
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=100)),
                ('gst_score', models.IntegerField(default=100)),
                ('itr_score', models.IntegerField(default=100)),
                ('tds_score', models.IntegerField(default=100)),
                ('documentation_score', models.IntegerField(default=100)),
                ('late_filings', models.IntegerField(default=0)),
                ('missing_documents', models.IntegerField(default=0)),
                ('compliance_issues', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compliance_scores',
            },
        ),
        migrations.CreateModel(
            name='GSTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('GSTR9', 'GSTR-9')], max_length=10)),
                ('period', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('late', 'Filed Late'), ('not_filed', 'Not Filed')], default='draft', max_length=20)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_input_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acknowledgment_number', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_returns',
            },
        ),
        migrations.CreateModel(
            name='ITRFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(max_length=10)),
                ('itr_form', models.CharField(choices=[('ITR1', 'ITR-1 (Sahaj)'), ('ITR2', 'ITR-2'), ('ITR3', 'ITR-3'), ('ITR4', 'ITR-4 (Sugam)')], max_length=10)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('processed', 'Processed'), ('refund', 'Refund Issued'), ('demand', 'Tax Demand')], default='draft', max_length=20)),
                ('gross_total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_computed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acknowledgment_number', models.CharField(blank=True, max_length=100)),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'itr_filings',
            },
        ),
        migrations.CreateModel(
            name='TaxCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calculation_type', models.CharField(choices=[('income_tax', 'Income Tax'), ('gst', 'GST'), ('tds', 'TDS'), ('professional_tax', 'Professional Tax')], max_length=30)),
                ('applicable_year', models.CharField(max_length=10)),
                ('tax_slabs', models.JSONField(default=list)),
                ('deductions', models.JSONField(default=list)),
                ('exemptions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tax_calculators',
            },
        ),
    ]
