# Generated by Django 4.2.7 on 2025-12-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itrfiling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itr_filings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancescore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancecalendar',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancerule'),
        ),
        migrations.AddField(
            model_name='compliancecalendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='itrfiling',
            unique_together={('user', 'assessment_year')},
        ),
        migrations.AlterUniqueTogether(
            name='gstreturn',
            unique_together={('user', 'return_type', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='compliancecalendar',
            unique_together={('user', 'rule', 'due_date')},
        ),
    ]
