# Generated by Django 4.2.7 on 2026-03-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0003_client_transaction_tdsrecord_report_notice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_messages', to='compliance.report'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdsrecord',
            name='pan_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tdsrecord',
            name='payment_type',
            field=models.CharField(choices=[('194J', 'Professional Fees (194J)'), ('194C', 'Contractor Payments (194C)'), ('194H', 'Commission/Brokerage (194H)'), ('194I', 'Rent (194I)'), ('194A', 'Interest Other than Securities (194A)')], default='194J', max_length=10),
        ),
        migrations.AddField(
            model_name='tdsrecord',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
